const ENTITIES = {
  departamento: {
    tableName: "Departamento",
    primaryKey: "id_departamento",
    columns: ["id_departamento", "nombre", "codigo"],
    requiredFields: ["id_departamento", "nombre", "codigo"],
    routesPath: "/departamentos",
  },
  municipio: {
    tableName: "Municipio",
    primaryKey: "id_municipio",
    columns: ["id_municipio", "nombre", "codigo", "departamento_id_departamento"],
    requiredFields: ["id_municipio", "nombre", "codigo", "departamento_id_departamento"],
    routesPath: "/municipios",
    foreignKeys: {
      departamento_id_departamento: "departamento",
    },
  },
  centroEvaluacion: {
    tableName: "Centro_Evaluacion",
    primaryKey: "id_centro",
    columns: ["id_centro", "nombre"],
    requiredFields: ["id_centro", "nombre"],
    routesPath: "/centros-evaluacion",
  },
  escuela: {
    tableName: "Escuela",
    primaryKey: "id_escuela",
    columns: ["id_escuela", "nombre", "direccion", "acuerdo"],
    requiredFields: ["id_escuela", "nombre", "acuerdo"],
    routesPath: "/escuelas",
  },
  ubicacion: {
    tableName: "Ubicacion",
    primaryKey: null,
    columns: ["escuela_id_escuela", "centro_id_centro"],
    requiredFields: ["escuela_id_escuela", "centro_id_centro"],
    routesPath: "/ubicaciones",
    foreignKeys: {
      escuela_id_escuela: "escuela",
      centro_id_centro: "centroEvaluacion",
    },
    isJoinTable: true,
  },
  tipoLicencia: {
    tableName: "Tipo_Licencia",
    primaryKey: "id_licencia",
    columns: ["id_licencia", "letra"],
    requiredFields: ["id_licencia", "letra"],
    routesPath: "/tipos-licencia",
  },
  tipoTramite: {
    tableName: "Tipo_Tramite",
    primaryKey: "id_tramite",
    columns: ["id_tramite", "descripcion"],
    requiredFields: ["id_tramite", "descripcion"],
    routesPath: "/tipos-tramite",
  },
  registro: {
    tableName: "Registro",
    primaryKey: "id_registro",
    columns: [
      "id_registro",
      "ubicacion_escuela_id_escuela",
      "ubicacion_centro_id_centro",
      "municipio_id_municipio",
      "municipio_departamento_id_departamento",
      "fecha",
      "tipo_tramite",
      "tipo_licencia",
      "nombre_completo",
      "genero",
    ],
    requiredFields: [
      "id_registro",
      "ubicacion_escuela_id_escuela",
      "ubicacion_centro_id_centro",
      "municipio_id_municipio",
      "municipio_departamento_id_departamento",
      "fecha",
      "tipo_tramite",
      "tipo_licencia",
      "nombre_completo",
      "genero",
    ],
    routesPath: "/registros",
    foreignKeys: {
      ubicacion_escuela_id_escuela: "escuela",
      ubicacion_centro_id_centro: "centroEvaluacion",
      municipio_id_municipio: "municipio",
    },
  },
  correlativo: {
    tableName: "Correlativo",
    primaryKey: "id_correlativo",
    columns: ["id_correlativo", "fecha", "no_examen"],
    requiredFields: ["id_correlativo", "fecha", "no_examen"],
    routesPath: "/correlativos",
  },
  examen: {
    tableName: "Examen",
    primaryKey: "id_examen",
    columns: [
      "id_examen",
      "registro_id_registro",
      "correlativo_id_correlativo",
      "registro_id_escuela",
      "registro_id_centro",
      "registro_municipio_id_municipio",
      "registro_municipio_departamento_id_departamento",
    ],
    requiredFields: [
      "id_examen",
      "registro_id_registro",
      "correlativo_id_correlativo",
      "registro_id_escuela",
      "registro_id_centro",
      "registro_municipio_id_municipio",
      "registro_municipio_departamento_id_departamento",
    ],
    routesPath: "/examenes",
    foreignKeys: {
      registro_id_registro: "registro",
      correlativo_id_correlativo: "correlativo",
    },
  },
  pregunta: {
    tableName: "Pregunta",
    primaryKey: "id_pregunta",
    columns: ["id_pregunta", "pregunta_texto", "respuesta_a", "respuesta_b", "respuesta_c", "respuesta_d", "respuesta_correcta"],
    requiredFields: ["id_pregunta", "pregunta_texto", "respuesta_a", "respuesta_b", "respuesta_c", "respuesta_d", "respuesta_correcta"],
    routesPath: "/preguntas",
  },
  preguntaPractico: {
    tableName: "Pregunta_Practico",
    primaryKey: "id_pregunta_practico",
    columns: ["id_pregunta_practico", "pregunta_texto", "punteo"],
    requiredFields: ["id_pregunta_practico", "pregunta_texto", "punteo"],
    routesPath: "/preguntas-practicas",
  },
  respuestaUsuario: {
    tableName: "Respuesta_Usuario",
    primaryKey: null,
    columns: ["pregunta_id_pregunta", "examen_id_examen", "respuesta"],
    requiredFields: ["pregunta_id_pregunta", "examen_id_examen", "respuesta"],
    routesPath: "/respuestas-usuario",
    foreignKeys: {
      pregunta_id_pregunta: "pregunta",
      examen_id_examen: "examen",
    },
    isJoinTable: true,
  },
  respuestaPracticoUsuario: {
    tableName: "Respuesta_Practico_Usuario",
    primaryKey: null,
    columns: ["pregunta_practico_id_pregunta_practico", "examen_id_examen", "nota"],
    requiredFields: ["pregunta_practico_id_pregunta_practico", "examen_id_examen", "nota"],
    routesPath: "/respuestas-practico-usuario",
    foreignKeys: {
      pregunta_practico_id_pregunta_practico: "preguntaPractico",
      examen_id_examen: "examen",
    },
    isJoinTable: true,
  },
};

module.exports = { ENTITIES };