-- Crear usuario de aplicación
-- Ejecutado con privilegios SYSDBA

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Verificar si el usuario existe y eliminarlo
BEGIN
  EXECUTE IMMEDIATE 'DROP USER C123 CASCADE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1918 THEN
    RAISE;
  END IF;
END;
/

-- Crear usuario
CREATE USER C123 IDENTIFIED BY "12345";

-- Conceder permisos esenciales
GRANT CONNECT TO C123;
GRANT RESOURCE TO C123;
GRANT DBA TO C123;
GRANT UNLIMITED TABLESPACE TO C123;

-- Conceder permisos explícitos para conectar
GRANT CREATE SESSION TO C123;
GRANT CREATE TABLE TO C123;
GRANT CREATE VIEW TO C123;
GRANT CREATE PROCEDURE TO C123;
GRANT CREATE SEQUENCE TO C123;

COMMIT;
/

SHOW USER;
/
