-- Script de inicialización de BD
-- Crea usuario C123 y todas las tablas en su schema

-- ============================================
-- PARTE 1: CREAR USUARIO (ejecutado como SYS)
-- ============================================

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- Eliminar usuario si existe
BEGIN
  EXECUTE IMMEDIATE 'DROP USER C123 CASCADE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1918 THEN
    RAISE;
  END IF;
END;
/

-- Crear usuario C123
CREATE USER C123 IDENTIFIED BY "12345";

-- Conceder permisos
GRANT CONNECT TO C123;
GRANT RESOURCE TO C123;
GRANT DBA TO C123;
GRANT UNLIMITED TABLESPACE TO C123;
GRANT CREATE SESSION TO C123;
GRANT CREATE TABLE TO C123;
GRANT CREATE VIEW TO C123;
GRANT CREATE PROCEDURE TO C123;
GRANT CREATE SEQUENCE TO C123;

COMMIT;
/

-- Cambiar sesión al usuario C123 para crear las tablas
CONNECT C123/12345@localhost:1521/xe;

-- ============================================
-- PARTE 2: CREAR TABLAS (ejecutado como C123)
-- ============================================

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-26 23:04:06 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE Centro_Evaluacion
    (
     id_centro INTEGER  NOT NULL ,
     nombre    VARCHAR2 (200) ,
     direccion VARCHAR2 (200)
    )
;

ALTER TABLE Centro_Evaluacion
    ADD CONSTRAINT Centro_Evaluacion_PK PRIMARY KEY ( id_centro ) ;

CREATE TABLE Departamento
    (
     id_departamento INTEGER  NOT NULL ,
     nombre          VARCHAR2 (50)
    )
;

ALTER TABLE Departamento
    ADD CONSTRAINT Departamento_PK PRIMARY KEY ( id_departamento ) ;

CREATE TABLE Escuela
    (
     id_escuela          INTEGER  NOT NULL ,
     nombre              VARCHAR2 (100) ,
     direccion           VARCHAR2 (200) ,
     numero_autorizacion VARCHAR2 (50)
    )
;

ALTER TABLE Escuela
    ADD CONSTRAINT Escuela_PK PRIMARY KEY ( id_escuela ) ;

CREATE TABLE Evaluacion
    (
     id_evaluacion               INTEGER  NOT NULL ,
     correlativo_diario          INTEGER ,
     fecha_evaluacion            DATE ,
     fecha_registro              DATE ,
     resultado_teorico           INTEGER ,
     resultado_practico          INTEGER ,
     Persona_id_persona          INTEGER  NOT NULL ,
     Centro_Evaluacion_id_centro INTEGER  NOT NULL ,
     Usuario_Sistema_id_usuario  INTEGER  NOT NULL
    )
;

ALTER TABLE Evaluacion
    ADD CONSTRAINT Evaluacion_PK PRIMARY KEY ( id_evaluacion ) ;

CREATE TABLE Evaluacion_Practica
    (
     id_epractica             INTEGER  NOT NULL ,
     puntaje_total            INTEGER ,
     Evaluacion_id_evaluacion INTEGER  NOT NULL
    )
;
CREATE UNIQUE INDEX Evaluacion_Practica__IDX ON Evaluacion_Practica
    (
     Evaluacion_id_evaluacion ASC
    )
;

ALTER TABLE Evaluacion_Practica
    ADD CONSTRAINT Evaluacion_Practica_PK PRIMARY KEY ( id_epractica ) ;

CREATE TABLE Evaluacion_Teorica
    (
     id_eteorica              INTEGER  NOT NULL ,
     puntaje_total            INTEGER ,
     Evaluacion_id_evaluacion INTEGER  NOT NULL
    )
;
CREATE UNIQUE INDEX Evaluacion_Teorica__IDX ON Evaluacion_Teorica
    (
     Evaluacion_id_evaluacion ASC
    )
;

ALTER TABLE Evaluacion_Teorica
    ADD CONSTRAINT Evaluacion_Teorica_PK PRIMARY KEY ( id_eteorica ) ;

CREATE TABLE Instructor
    (
     id_instructor         INTEGER  NOT NULL ,
     nombre                VARCHAR2 (150) ,
     identificacion        VARCHAR2 (50) ,
     eval_prac_id          INTEGER  NOT NULL
    )
;

ALTER TABLE Instructor
    ADD CONSTRAINT Instructor_PK PRIMARY KEY ( id_instructor ) ;

CREATE TABLE Municipio
    (
     id_municipio                 INTEGER  NOT NULL ,
     nombre                       VARCHAR2 (50) ,
     Departamento_id_departamento INTEGER  NOT NULL
    )
;

ALTER TABLE Municipio
    ADD CONSTRAINT Municipio_PK PRIMARY KEY ( id_municipio ) ;

CREATE TABLE Persona
    (
     id_persona                INTEGER  NOT NULL ,
     nombre_completo           VARCHAR2 (150) ,
     identificacion            VARCHAR2 (50) ,
     direccion                 VARCHAR2 (200) ,
     telefono                  VARCHAR2 (20) ,
     genero                    CHAR (1) ,
     fecha_nacimiento          DATE ,
     fotografia                BLOB ,
     Municipio_id_municipio    INTEGER  NOT NULL ,
     Escuela_id_escuela        INTEGER  NOT NULL ,
     Tipo_Licencia_id_licencia INTEGER  NOT NULL ,
     Tipo_Tramite_id_tramite   INTEGER  NOT NULL
    )
;

ALTER TABLE Persona
    ADD CONSTRAINT Persona_PK PRIMARY KEY ( id_persona ) ;

CREATE TABLE Pregunta_Teorica
    (
     id_pregunta                    INTEGER  NOT NULL ,
     texto                          VARCHAR2 (500) ,
     imagen                         BLOB ,
     Evaluacion_Teorica_id_eteorica INTEGER  NOT NULL
    )
;

ALTER TABLE Pregunta_Teorica
    ADD CONSTRAINT Pregunta_Teorica_PK PRIMARY KEY ( id_pregunta ) ;

CREATE TABLE Relation_1
    (
     Escuela_id_escuela          INTEGER  NOT NULL ,
     Centro_Evaluacion_id_centro INTEGER  NOT NULL
    )
;

ALTER TABLE Relation_1
    ADD CONSTRAINT Relation_1_PK PRIMARY KEY ( Escuela_id_escuela, Centro_Evaluacion_id_centro ) ;

CREATE TABLE Respuesta_Teorica
    (
     id_respuesta                 INTEGER  NOT NULL ,
     texto                        VARCHAR2 (500) ,
     imagen                       BLOB ,
     es_correcta                  CHAR (1) ,
     Pregunta_Teorica_id_pregunta INTEGER  NOT NULL
    )
;

ALTER TABLE Respuesta_Teorica
    ADD CONSTRAINT Respuesta_Teorica_PK PRIMARY KEY ( id_respuesta ) ;

CREATE TABLE Tipo_Licencia
    (
     id_licencia INTEGER  NOT NULL ,
     letra       CHAR (1)
    )
;

ALTER TABLE Tipo_Licencia
    ADD CONSTRAINT Tipo_Licencia_PK PRIMARY KEY ( id_licencia ) ;

CREATE TABLE Tipo_Tramite
    (
     id_tramite  INTEGER  NOT NULL ,
     descripcion VARCHAR2 (50)
    )
;

ALTER TABLE Tipo_Tramite
    ADD CONSTRAINT Tipo_Tramite_PK PRIMARY KEY ( id_tramite ) ;

CREATE TABLE Usuario_Sistema
    (
     id_usuario INTEGER  NOT NULL ,
     nombre     VARCHAR2 (50)
    )
;

ALTER TABLE Usuario_Sistema
    ADD CONSTRAINT Usuario_Sistema_PK PRIMARY KEY ( id_usuario ) ;

-- Foreign Keys
ALTER TABLE Evaluacion
    ADD CONSTRAINT Eval_Centro_FK FOREIGN KEY
    (
     Centro_Evaluacion_id_centro
    )
    REFERENCES Centro_Evaluacion
    (
     id_centro
    )
;

ALTER TABLE Evaluacion
    ADD CONSTRAINT Evaluacion_Persona_FK FOREIGN KEY
    (
     Persona_id_persona
    )
    REFERENCES Persona
    (
     id_persona
    )
;

ALTER TABLE Evaluacion_Practica
    ADD CONSTRAINT EPrac_Eval_FK FOREIGN KEY
    (
     Evaluacion_id_evaluacion
    )
    REFERENCES Evaluacion
    (
     id_evaluacion
    )
;

ALTER TABLE Evaluacion_Teorica
    ADD CONSTRAINT ETeo_Eval_FK FOREIGN KEY
    (
     Evaluacion_id_evaluacion
    )
    REFERENCES Evaluacion
    (
     id_evaluacion
    )
;

ALTER TABLE Evaluacion
    ADD CONSTRAINT Evaluacion_Usuario_Sistema_FK FOREIGN KEY
    (
     Usuario_Sistema_id_usuario
    )
    REFERENCES Usuario_Sistema
    (
     id_usuario
    )
;

ALTER TABLE Instructor
    ADD CONSTRAINT Instr_EPrac_FK FOREIGN KEY
    (
     eval_prac_id
    )
    REFERENCES Evaluacion_Practica
    (
     id_epractica
    )
;

ALTER TABLE Municipio
    ADD CONSTRAINT Municipio_Departamento_FK FOREIGN KEY
    (
     Departamento_id_departamento
    )
    REFERENCES Departamento
    (
     id_departamento
    )
;

ALTER TABLE Persona
    ADD CONSTRAINT Persona_Escuela_FK FOREIGN KEY
    (
     Escuela_id_escuela
    )
    REFERENCES Escuela
    (
     id_escuela
    )
;

ALTER TABLE Persona
    ADD CONSTRAINT Persona_Municipio_FK FOREIGN KEY
    (
     Municipio_id_municipio
    )
    REFERENCES Municipio
    (
     id_municipio
    )
;

ALTER TABLE Persona
    ADD CONSTRAINT Persona_Tipo_Licencia_FK FOREIGN KEY
    (
     Tipo_Licencia_id_licencia
    )
    REFERENCES Tipo_Licencia
    (
     id_licencia
    )
;

ALTER TABLE Persona
    ADD CONSTRAINT Persona_Tipo_Tramite_FK FOREIGN KEY
    (
     Tipo_Tramite_id_tramite
    )
    REFERENCES Tipo_Tramite
    (
     id_tramite
    )
;

ALTER TABLE Pregunta_Teorica
    ADD CONSTRAINT PTeo_ETeo_FK FOREIGN KEY
    (
     Evaluacion_Teorica_id_eteorica
    )
    REFERENCES Evaluacion_Teorica
    (
     id_eteorica
    )
;

ALTER TABLE Relation_1
    ADD CONSTRAINT Rel1_Centro_FK FOREIGN KEY
    (
     Centro_Evaluacion_id_centro
    )
    REFERENCES Centro_Evaluacion
    (
     id_centro
    )
;

ALTER TABLE Relation_1
    ADD CONSTRAINT Relation_1_Escuela_FK FOREIGN KEY
    (
     Escuela_id_escuela
    )
    REFERENCES Escuela
    (
     id_escuela
    )
;

ALTER TABLE Respuesta_Teorica
    ADD CONSTRAINT RTeo_PTeo_FK FOREIGN KEY
    (
     Pregunta_Teorica_id_pregunta
    )
    REFERENCES Pregunta_Teorica
    (
     id_pregunta
    )
;

COMMIT;
/
